# Generated by Django 5.0.6 on 2024-06-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('PESEL', models.CharField(max_length=11)),
                ('birth_name', models.CharField(max_length=40)),
                ('adres', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('diagnosis', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('team_leader', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='key_words',
            new_name='KeyWord',
        ),
        migrations.RenameModel(
            old_name='laboratories',
            new_name='Laboratory',
        ),
        migrations.RenameModel(
            old_name='metody',
            new_name='Method',
        ),
        migrations.DeleteModel(
            name='Employes',
        ),
        migrations.DeleteModel(
            name='patients',
        ),
        migrations.DeleteModel(
            name='personal_inf',
        ),
        migrations.DeleteModel(
            name='projects',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
        migrations.AddField(
            model_name='employee',
            name='mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekty.user'),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekty.employee'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekty.patient'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ManyToManyField(to='projekty.project'),
        ),
    ]
