# Generated by Django 5.0.6 on 2024-06-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0002_employee_patient_project_rename_key_words_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mail',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekty.method'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
