# Generated by Django 5.0.6 on 2024-06-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0005_alter_experiment_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PESEL',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mail',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
