# Generated by Django 5.0.6 on 2024-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0007_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=1, null=True),
        ),
    ]
